import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateOrderExtraCostApprovals1716000000026 implements MigrationInterface {
  name = 'CreateOrderExtraCostApprovals1716000000026';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "order_schema"."order_extra_cost_approvals" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "is_deleted" boolean NOT NULL DEFAULT false,
        "order_id" bigint NOT NULL,
        "market_id" bigint NOT NULL,
        "requested_by_user_id" bigint NOT NULL,
        "requested_by_role" character varying(40) NULL,
        "requester_branch_id" bigint NULL,
        "action" character varying(20) NOT NULL,
        "amount" numeric(14,2) NOT NULL DEFAULT 0,
        "proof_file_keys" jsonb NULL,
        "operation_payload" jsonb NOT NULL,
        "status" character varying(20) NOT NULL DEFAULT 'pending',
        "decided_by_user_id" bigint NULL,
        "decided_at" TIMESTAMPTZ NULL,
        "decision_comment" text NULL,
        CONSTRAINT "PK_order_extra_cost_approvals" PRIMARY KEY ("id")
      );
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_ORDER_EXTRA_COST_APPROVAL_MARKET_STATUS"
      ON "order_schema"."order_extra_cost_approvals"
        ("market_id", "status", "createdAt" DESC);
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_ORDER_EXTRA_COST_APPROVAL_ORDER_STATUS"
      ON "order_schema"."order_extra_cost_approvals" ("order_id", "status");
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS "order_schema"."order_extra_cost_approvals";
    `);
  }
}
