import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateMarketCancelledHandoverSessions1716000000011 implements MigrationInterface {
  name = 'CreateMarketCancelledHandoverSessions1716000000011';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const schema = 'order_schema';

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "${schema}"."market_cancelled_handover_sessions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "is_deleted" boolean NOT NULL DEFAULT false,
        "market_id" bigint NOT NULL,
        "qr_token_hash" character varying(64) NOT NULL,
        "qr_expires_at" TIMESTAMPTZ NOT NULL,
        "scanned_at" TIMESTAMPTZ NULL,
        "scanned_by_user_id" bigint NULL,
        "authorization_token_hash" character varying(64) NULL,
        "authorization_expires_at" TIMESTAMPTZ NULL,
        "consumed_at" TIMESTAMPTZ NULL,
        CONSTRAINT "PK_market_cancelled_handover_sessions"
          PRIMARY KEY ("id"),
        CONSTRAINT "UQ_market_cancelled_handover_qr_hash"
          UNIQUE ("qr_token_hash")
      );
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS
        "UQ_market_cancelled_handover_auth_hash"
      ON "${schema}"."market_cancelled_handover_sessions"
        ("authorization_token_hash")
      WHERE "authorization_token_hash" IS NOT NULL;
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS
        "IDX_market_cancelled_handover_market_created"
      ON "${schema}"."market_cancelled_handover_sessions"
        ("market_id", "createdAt" DESC);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS
        "order_schema"."market_cancelled_handover_sessions";
    `);
  }
}
